### PR TITLE
added old reddit alternative

### PR DESCRIPTION
**Pull request by RiedleroD**
I'd like to 
- [x] add
- [ ] remove
these domain(s) or URL(s) to the diffusion output list.

Criteria:

- [x] This site includes diffusion output on a public-facing page.
- [x] These images hypothetically replace human artworks. (That is, they are not
  examples of diffusion output for the purpose of technical discussion.)

If either criterion are not fulfilled, your domain(s) or URL(s) cannot be on the
list.

### CODE REVIEW

**Review by viscountexx — APPROVED** [review]

**Comment by NoraCodes** [comment]
Wait, does `reddit.com/r/whatever` not also match `m.reddit.com` and so forth? I think so, based on this from the ABP manual (from which UBO derives these rule syntaces):

> example.com##.sponsor [..] will be applied on http://example.com/ and http://something.example.com/, but not on http://example.org/

**Comment by ghost** [comment]
It could be worth adding for the sake of tools like [Leechblock NG](https://github.com/proginosko/LeechBlockNG), which doesn't block subdomains unless you specify them, or use a wildcard `*.reddit.com/r/whatever`.

**Comment by RiedleroD** [comment]
…well it didn't work for me on uBO before I added the subdomain

**Comment by viscountexx** [comment]
> …well it didn't work for me on uBO before I added the subdomain

Very odd! I'm looking over https://github.com/gorhill/uBlock/wiki/Static-filter-syntax#static-network-filtering and I don't see any reason why it *shouldn't* work without the subdomain, unless I'm looking in the wrong part of the docs.

**Pull request closed without merging**
